In [1]:
import soundfile as sf
import librosa

In [20]:
left_inp = librosa.load('onlyleft_input_binaural.wav', sr=16000, mono=False)[0]
right_inp = librosa.load('onlyright_input_binaural.wav', sr=16000, mono=False)[0]
left_pred = librosa.load('onlyleft_predicted_binaural.wav', sr=16000, mono=False)[0]
right_pred = librosa.load('onlyright_predicted_binaural.wav', sr=16000, mono=False)[0]
left_mix = librosa.load('onlyleft_mixed_mono.wav', sr=16000, mono=False)[0]
right_mix = librosa.load('onlyright_mixed_mono.wav', sr=16000, mono=False)[0]
inp = librosa.load('input_binaural.wav', sr=16000, mono=False)[0]
pred = librosa.load('predicted_binaural.wav', sr=16000, mono=False)[0]
mix = librosa.load('mixed_mono.wav', sr=16000, mono=False)[0]

In [21]:
left_inp

array([[-0.04089355, -0.06829834, -0.06411743, ..., -0.03417969,
         0.00506592, -0.00201416],
       [-0.04089355, -0.06829834, -0.06411743, ..., -0.03417969,
         0.00506592, -0.00201416]], dtype=float32)

In [22]:
right_inp

array([[-0.02832031, -0.03305054, -0.00692749, ...,  0.04016113,
         0.01889038, -0.00027466],
       [-0.02832031, -0.03305054, -0.00692749, ...,  0.04016113,
         0.01889038, -0.00027466]], dtype=float32)

In [23]:
left_mix

array([-0.04089355, -0.06829834, -0.06411743, ..., -0.03417969,
        0.00506592, -0.00201416], dtype=float32)

In [24]:
right_mix

array([-0.02832031, -0.03305054, -0.00692749, ...,  0.04016113,
        0.01889038, -0.00027466], dtype=float32)

In [25]:
left_pred

array([[-0.0721283 , -0.10124946, -0.09683967, ..., -0.03593278,
        -0.06414473, -0.05196488],
       [-0.00965893, -0.03534734, -0.03139532, ..., -0.02459502,
        -0.05661178, -0.04337227]], dtype=float32)

In [26]:
right_pred

array([[-0.03992093, -0.04359603, -0.01238811, ...,  0.01650918,
         0.05826414,  0.05578768],
       [-0.01671982, -0.02250516, -0.00146699, ...,  0.00414538,
         0.04288888,  0.03470492]], dtype=float32)

In [27]:
pred

array([[-0.05718887, -0.07336044, -0.05579996, ..., -0.00802398,
        -0.00385249, -0.00123024],
       [-0.01202512, -0.02798855, -0.01524508, ..., -0.01209378,
        -0.00661123, -0.00176799]], dtype=float32)

In [15]:
import numpy as np
def cal_normdiff(a, b):
    return np.linalg.norm(a - b)


In [18]:
cal_normdiff(left_pred, left_inp)

20.411007

In [19]:
cal_normdiff(right_pred, right_inp)

8.255097

In [28]:
cal_normdiff(pred, inp)

15.363849

In [30]:
cal_normdiff(left_pred, inp)

27.231007

In [31]:
cal_normdiff(right_pred, inp)

26.942867

In [32]:
cal_normdiff(pred, inp)

15.363849

In [ ]:
cal_normdiff(left_pred,